#------------------------
#GitHub Actions Part 1
#------------------------

name: My_GitHub Actions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{  github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello world from Testing job"

    - name: Print few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name is ${{ env.APPLICATION_NAME }}"

    - name: list current folder
      run : ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: list current folder
      run : ls -la
    
  my_deployment:
      runs-on: ubuntu-latest
      env:
        VAR_1: "Sam"
  
      steps:
      - name: Print Hello Message in Deployment
        run: echo "Hello world from Deployment job"

      - name: Printing first variable
        env:
          LocalVAR: 'Super Local VAR'
        run : |
          echo "First var"
          echo "First var is ${{ env.VAR_1 }}"
          echo "VAR2 is $LocalVAR"
          

      - name: Print few commands
        run: |
          echo "Hello deploy message1"
          echo "Hello deploy message2"
          echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Lets test some packages if there are here 1
        run : aws --version

      - name: Lets test some packages if there are here 2
        run : zip --version

