#------------------------
#GitHub Actions Part 1
#------------------------

name: My_GitHub Actions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{  github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello world from Testing job"

    - name: Print few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name is ${{ env.APPLICATION_NAME }}"

  my_deployment:
      runs-on: ubuntu-latest
  
      steps:
      - name: Print Hello Message in Deployment
        run: echo "Hello world from Deployment job"
